apiVersion: v1
kind: Service
metadata:
  name: app-mock-jira-service
  labels:
    name: app-mock-jira-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4545
      targetPort: 4545
      nodePort: 32123
  selector:
    run: app-mock-jira
